<?php $cats = array('Group' => $this->groups, 'Cat' => $this->cats); ?>
<!DOCTYPE html>
<html>
	<head>
		<title><?php echo SYSTEM_NAME; ?> :: Admin Panel</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="author" content="Denver Freeburn">
		<link rel="stylesheet" type="text/css" href="<?php echo SYSTEM_URL; ?>asset/styles/<?php echo strtolower(SYSTEM_THEME); ?>/core.css">
		<link rel="stylesheet" type="text/css" href="<?php echo SYSTEM_URL; ?>asset/styles/<?php echo strtolower(SYSTEM_THEME); ?>/hg.css">
		<link rel="stylesheet" type="text/css" href="<?php echo SYSTEM_URL; ?>asset/styles/<?php echo strtolower(SYSTEM_THEME); ?>/admin.css">
		<style type="application/javascript" src="<?php echo SYSTEM_URL; ?>asset/scripts/core.js"></style>
	</head>
	
	<body>
		<div id="wrap">
			<div id="content">
				<div class="header">
					<div class="logo inblk">
						<?php echo SYSTEM_NAME; ?>
					</div>
					<div class="other-part inblk">
						<div class="contact">
							<strong>P: 07871 350197</strong><br />
							<strong>E: hampersgalore@hotmail.com</strong>
						</div>
					</div>
				</div>
				<div class="nav-bar">
					<ul>
						<li><a href="/index.php">Home</a></li>
					</ul>
				</div>
				<div class="content-wrapper inblk">
					<?php if(isset($this->errmsg)): ?>
						<div class="alert alert-danger"><?php echo $this->errmsg; ?></div>
					<?php unset($this->errmsg); endif;?>
					
					<?php echo $this->content_for_template; ?>
				</div>
				<div class="footer">
					&copy; Hampers Galore <?php echo date("Y"); ?> - All Rights Reserved.<br />
					<a href="http://github.com/gnrdenver/cisium">Cisium</a> ECommerce platform by Denver Freeburn
				</div>
			</div>
		</div>
	</body>
</html>