<div class="panel panel-primary panel-inside">
	<div class="panel-heading"><h3>Credits</h3></div>
	<div style="margin: 5px;">
		<h3>Denver Freeburn</h3>
		<p><a href="mailto:denver@denverfreeburn.com">denver@denverfreeburn.com</a></p>
		<p class="text text-muted">Denver is the lead developer on the Caruca Project.</p>
		<div class="well well-sm">
			Denver came up with the idea to build an online shopping cart program to help further
			his knowledge with the PHP Programming Language and the MySQL Database Server. Soon after
			beginning this cart, he was approached by several people interested in using it for their
			online store, thus kickstarting him to work on it every night instead of just one or two
			nights per week.
		</div>
		<hr>
		<h3>Stevan Goode</h3>
		<p><a href="mailto:stevan@stevangoode.com">stevan@stevangoode.com</a></p>
		<p class="text text-muted">Stevan helped with debugging several aspects of the program.</p>
		<div class="well well-sm">
			<p>
				Stevan has 10+ years of knowledge with PHP &amp; MySQL and as such, was valuable during the
				debugging phase of the program.
			</p>
			<p>Stevan can be hired to program for you. To enquire, use the email address listed above.</p>
		</div>
		<hr>
		<h3>Twitter Bootstrap</h3>
		<p><a href="http://getbootstrap.php">Visit Website</a></p>
		<p class="text text-muted">Much of the theme was built using the Twitter Bootstrap library.</p>
		<hr>
		<h3>Dagon</h3>
		<p><a href="http://stackoverflow.com/users/557846/dagon">Dagon @ StackOverflow.com</a></p>
		<div class="well well-sm">
			<p>
				Dagon helped me with a few issues in the cart.
			</p>
		</div>
	</div>
</div>