<div class="panel panel-primary">
	<div class="panel-heading"><h3>Log In</h3></div>
	<form action="/admin/index.php" method="post" autocomplete="off">
		<div class="group-block">
			<label for="email">Email Address</label>
			<input type="email" id="email" name="email" class="form-control input-lg">
		</div>
		<div class="group-block">
			<label for="password">Password</label>
			<input type="password" id="password" name="password" class="form-control input-lg">
		</div>
		<div class="group-block">
			<p></p>
			<button type="submit" class="btn btn-success btn-block">Log In</button>
		</div>
	</form>
</div>