<form class="signup" method="post" action="<?php echo SYSTEM_URL; ?>signin.php">
	<fieldset>
		<legend>Client Details</legend>
		<div class="form-section inblk">
			<label for="email">Email</label>
			<input type="email" name="email" id="email" class="input-xlarge" placeholder="Email">
		</div>
		<div class="form-section inblk">
			<label for="password">Password</label>
			<input type="password" name="password" id="password" class="input-xlarge" placeholder="Password">
		</div>
		<div class="form-section-btn">
			<button type="submit" class="btn btn-block">Sign In</button>
		</div>
	</fieldset>
</form>