<form class="signup" method="post" action="<?php echo SYSTEM_URL; ?>signup.php">
	<fieldset>
		<legend>Client Details</legend>
		<div class="form-section inblk">
			<label for="firstname">First Name</label>
			<input type="text" name="firstname" id="firstname" class="input-xlarge" placeholder="First Name">
		</div>
		<div class="form-section inblk">
			<label for="lastname">Last Name</label>
			<input type="text" name="lastname" id="lastname" class="input-xlarge" placeholder="Last Name">
		</div>
		<div class="form-section inblk">
			<label for="password">Password</label>
			<input type="password" name="password" id="password" class="input-xlarge" placeholder="Password">
		</div>
		<div class="form-section inblk">
			<label for="confirmpassword">Confirm Password</label>
			<input type="password" name="confirmpassword" id="confirmpassword" class="input-xlarge" placeholder="Confirm Password">
		</div>
		<div class="form-section inblk">
			<label for="email">Email</label>
			<input type="email" name="email" id="email" class="input-xlarge" placeholder="Email">
		</div>
		<div class="form-section inblk">
			<label for="phone">Phone Number (UK Only)</label>
			<input type="text" name="phone" id="phone" class="input-xlarge" placeholder="Phone Number">
		</div>
	</fieldset>
	<fieldset>
		<legend>Billing Address</legend>
		<div class="form-section inblk">
			<label for="line1">Address Line 1</label>
			<input type="text" name="line1" id="line1" class="input-xlarge" placeholder="Ex: Cherry House">
		</div>
		<div class="form-section inblk">
			<label for="line2">Address Line 2</label>
			<input type="text" name="line2" id="line2" class="input-xlarge" placeholder="Ex: 45 Main Street">
		</div>
		<div class="form-section inblk">
			<label for="city">City</label>
			<input type="text" name="city" id="city" class="input-xlarge" placeholder="Ex: London">
		</div>
		<div class="form-section inblk">
			<label for="county">County</label>
			<input type="text" name="county" id="county" class="input-xlarge" placeholder="Ex: London">
		</div>
		<div class="form-section inblk">
			<label for="country">Country</label>
			<input type="text" name="country" id="country" class="input-xlarge" placeholder="Ex: United Kingdom">
		</div>
		<div class="form-section inblk">
			<label for="postcode">Post/Zip Code</label>
			<input type="text" name="postcode" id="postcode" class="input-xlarge" placeholder="Ex: E1 3LD">
		</div>
		<div class="form-section-btn">
			<button type="submit" class="btn btn-block">Sign Up</button>
		</div>
	</fieldset>
</form>