<?php foreach($this->account as $user): ?>
<?php if($_GET['a'] == 'view'): ?>
<fieldset>
	<legend>Your Account : View</legend>
		<table class="table table-striped table-condensed table-bordered">
			<tr>
				<th>Your Name</th>
				<td><?php echo $user['client_firstname'].' '.$user['client_lastname']; ?></td>
			</tr>
			<tr>
				<th>Your Email Address</th>
				<td><?php echo $user['client_email']; ?></td>
			</tr>
			<tr>
				<th>Your Billing &amp; Shipping Address</th>
				<td>
					<?php echo $user['client_line1']; ?><br />
					<?php echo $user['client_line2']; ?><br />
					<?php echo $user['client_city']; ?><br />
					<?php echo $user['client_county']; ?><br />
					<?php echo $user['client_country']; ?><br />
					<?php echo $user['client_postcode']; ?>
				</td>
			</tr>
			<tr>
				<th>Your Phone Number</th>
				<td><?php echo $user['client_phone']; ?></td>
			</tr>
			<tr>
				<th>Your Payment Gateway</th>
				<td><?php echo $user['client_gw']; ?></td>
			</tr>
			<tr>
				<th>Member Since</th>
				<td><?php echo date("D, jS F Y", strtotime($user['client_joined'])); ?></td>
			</tr>
		</table>
		<span class="label label-warning"><a href="/account.php?a=edit">Edit Account</a></span>
		<span class="label label-success"><a href="/account.php?a=password">Edit Password</a></span>
		<span class="label label-danger"><a href="#" class="getInfo" data-lookup="accountdelete">Delete Account</a></span>
</fieldset>
<?php elseif($_GET['a'] == 'edit'): ?>
<fieldset>
	<legend>Your Account : Edit</legend>
	<form action="/account.php?<?php echo $_SERVER['QUERY_STRING']; ?>" method="post">
		<div class="panel panel-info panel-inside">
			<div class="panel-heading">My Details</div>
			<div class="form-group inblk">
				<label for="firstname">First Name</label>
				<input type="text" name="firstname" id="firstname" class="form-control wd-md" value="<?php echo $user['client_firstname']; ?>">
			</div>
			<div class="form-group inblk">
				<label for="lastname">Last Name</label>
				<input type="text" name="lastname" id="lastname" class="form-control wd-md" value="<?php echo $user['client_lastname']; ?>">
			</div>
			<div class="form-group inblk">
				<label for="email">Email Addresss</label>
				<input type="email" name="email" id="email" class="form-control wd-md" value="<?php echo $user['client_email']; ?>">
			</div>
			<div class="form-group inblk">
				<label for="phone">Phone Number</label>
				<input type="text" name="phone" id="phone" class="form-control wd-md" value="<?php echo $user['client_phone']; ?>">
			</div>
		</div>
		<div class="panel panel-success panel-inside">
			<div class="panel-heading">Billing &amp; Shipping</div>
			<div class="form-group inblk">
				<label for="line1">Line 1</label>
				<input type="text" name="line1" id="line1" class="form-control wd-md" value="<?php echo $user['client_line1']; ?>">
			</div>
			<div class="form-group inblk">
				<label for="line2">Line 2</label>
				<input type="text" name="line2" id="line2" class="form-control wd-md" value="<?php echo $user['client_line2']; ?>">
			</div>
			<div class="form-group inblk">
				<label for="city">City</label>
				<input type="text" name="city" id="city" class="form-control wd-md" value="<?php echo $user['client_city']; ?>">
			</div>
			<div class="form-group inblk">
				<label for="county">County</label>
				<input type="text" name="county" id="county" class="form-control wd-md" value="<?php echo $user['client_county']; ?>">
			</div>
			<div class="form-group inblk">
				<label for="country">Country</label>
				<input type="text" name="country" id="country" class="form-control wd-md" value="<?php echo $user['client_country']; ?>">
			</div>
			<div class="form-group inblk">
				<label for="postcode">Post/Zip Code</label>
				<input type="text" name="postcode" id="postcode" class="form-control wd-md" value="<?php echo $user['client_postcode']; ?>">
			</div>
			<div class="form-group inblk">
				<label for="payment">Payment Gateway</label>
				<select name="payment" id="payment" class="form-control wd-md">
					<?php foreach(json_decode($this->payment) as $payment): ?>
					<option selected value="<?php echo $payment->gw_name; ?>"><?php echo $payment->gw_vanity; ?></option>
					<?php endforeach; ?>
					<option disabled>----</option>
					<?php foreach(json_decode($this->gateways) as $gw): ?>
					<option value="<?php echo $gw->gw_name; ?>"><?php echo $gw->gw_vanity; ?></option>
					<?php endforeach; ?>
				</select>
			</div>
			<div class="panel-footer">
				<button type="submit" class="btn btn-success pull-right">Save Changes</button><div class="clearfix"></div>
			</div>
		</div>
	</form>
</fieldset>
<?php elseif($_GET['a'] == 'password'): ?>
<fieldset>
	<legend>Your Account : Password</legend>
	<div class="panel panel-danger panel-inside">
		<div class="panel-heading">Change Your Password</div>
		<form action="/account.php?<?php echo $_SERVER['QUERY_STRING']; ?>" method="post">
			<div class="form-group">
				<label for="oldpassword">Old Password</label>
				<input type="password" name="oldpassword" id="oldpassword" class="form-control wd-md" placeholder="Old Password">
			</div>
			<div class="form-group">
				<label for="password">New Password</label>
				<input type="password" name="newpassword" id="newpassword" class="form-control wd-md" placeholder="New Password">
			</div>
			<div class="form-group">
				<label for="password">Confirm New Password</label>
				<input type="password" name="confirmpassword" id="confirmpassword" class="form-control wd-md" placeholder="Confirm Password">
			</div>
			<div class="panel-footer">
				<button type="submit" class="btn btn-success pull-right">Save Changes</button><div class="clearfix"></div>
			</div>
		</form>
	</div>
</fieldset>
<?php endif; ?>
<?php endforeach; ?>