<h3>Hi, <?php echo $this->creds['client_firstname']; ?></h3>
<p class="text text-danger">
	<br>Sorry to hear you cancelled your order! :(<br>
</p>
<p class="text text-info">
	We have cleared your shopping cart for this session.
</p>
<hr>

<a href="/products.php" class="btn btn-default">&lt;- Continue Shopping</a>
<a href="/account.php?a=view" class="btn btn-default pull-right">My Account -&gt;</a>
<div class="clearfix"></div>
